const products = {
    data: [
      {
        id: "86jUSHR0xzdycpR",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/files/VitalSeamless2.0CropTop-GSDeepTeal-Marl-B1A3D-TBK1-0491_d0ea15a8-6b6b-41b4-848c-2f0fb5e19f75_1920x.jpg?v=1689235905",
        name: "VITAL SEAMLESS 2.0 CROP TOP",
        description: "Whatever conditioning means to you, Vital’s got something to help you feel, and perform, your best. Because you can do it all, and so can Vital.",
        category: "tops",
        color: "Deep Teal Marl",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
          { id: '6', size: 'XXL' },
        ],
        price: 35,
        ratings: 4.5,
        isInStock: true
      },
      {
        id: "K5SuC288DtkdikK",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/220713_VITAL_Neutrals_MB8890_ZH.jpg?v=1660208722",
        name: "VITAL SEAMLESS 2.0 CROP TOP",
        description: "Vital’s new neutrals have been made for your shade. You’ll still get the same sweat-wicking, breathable, and seamless designs as the rest of the collection, but these four neutral colors have been meticulously designed to complement a whole range of skin tones. Because if you feel your best, you’re gonna perform at your best. Because you’re not just allowed here, you belong here. Because you can do it all, and so can Vital.",
        category: "tops",
        color: "Espresso Marl",
        sizes: [
          { id: '1', size: 'S' },
          { id: '2', size: 'M' },
          { id: '3', size: 'L' },
        ],
        price: 35,
        ratings: 4.8,
        isInStock: true
      },
      {
        id: "hcl2nYTqrD4gzRG",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/files/VitalSeamlessWCropTopBrightFuchsia-MarlB1A3D-KBM5.116.jpg?v=1682435477",
        name: "VITAL SEAMLESS 2.0 CROP TOP",
        description: "Whatever conditioning means to you, Vital’s got something to help you feel, and perform, your best. Because you can do it all, and so can Vital.",
        category: "tops",
        color: "Bright Fuchsia Marl",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
          { id: '6', size: 'XXL' },
        ],
        price: 35,
        ratings: 4.5,
        isInStock: true
      },
      {
        id: "mrwAXaEJuvHj0Kr",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/VitalSeamlessWCropTopStellarBlue-MarlB1A3D-UBR3-2117_59e6a14f-d5ed-40bf-99eb-5fa957a74a4a.jpg?v=1665512280",
        name: "VITAL SEAMLESS 2.0 CROP TOP",
        description: "This product is made using dope dyeing technology that uses less water, energy and chemicals, as part of our sustainability strategy to lower environmental impact.",
        category: "tops",
        color: "Stellar Blue Marl",
        sizes: [
          { id: '1', size: 'XL' },
          { id: '2', size: 'XXL' },
        ],
        price: 35,
        ratings: 4.7,
        isInStock: true
      },
      {
        id: "4YwRa37T6c3uqy5",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/files/ADAPTFLECKSEAMLESSCROPTOPENG-L-A0015GSCobaltBlueGSIrisBlueB6A3B-UCBJ13.jpg?v=1688459080",
        name: "ADAPT FLECK SEAMLESS CROP TOP",
        description: "The collection made for lifting, flex on your latest ‘fit in Adapt Fleck.",
        category: "tops",
        color: "Cobalt Blue/Iris Blue",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
          { id: '6', size: 'XXL' },
        ],
        price: 35,
        ratings: 3.5,
        isInStock: true
      },
      {
        id: "VuaIoIzs53ZF7iu",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/IconTrendLeggingsBlack-B4A8U-BBBB-2393.272_87efb7a9-ba56-45a2-b6fd-33a332b00d88.jpg?v=1678114478",
        name: "CROSSOVER LEGGINGS",
        description: "These collections take your training staples and give you something a little bit extra.",
        category: "leggings",
        color: "Black",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
          { id: '6', size: 'XXL' },
        ],
        price: 40,
        ratings: 4.9,
        isInStock: true
      },
      {
        id: "4pqJf76btzL0lSJ",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/IconTrendLeggingsBrightFuchsia-B4A8U-KBPB-2233.251_21a4d35e-1de0-45a0-8e4a-4c0167684a4c.jpg?v=1678114478",
        name: "CROSSOVER LEGGINGS",
        description: "These collections take your training staples and give you something a little bit extra.",
        category: "leggings",
        color: "Bright Fuchsia",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 40,
        ratings: 4.3,
        isInStock: true
      },
      {
        id: "F9fKQPuVE8GS43w",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/IconTrendLeggingsBlack-B4A8U-BBBB-2393.272_87efb7a9-ba56-45a2-b6fd-33a332b00d88.jpg?v=1678114478",
        name: "FRACTION LEGGINGS",
        description: "A piece you can pair with anything doesn’t have to be boring. That’s where a Fraction look steps in: your new staple item.",
        category: "leggings",
        color: "Plum Pink",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
          { id: '6', size: 'XXL' },
        ],
        price: 45,
        ratings: 4.9,
        isInStock: true
      },
      {
        id: "3da2Vn5GjYPHoRk",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/IconRunningLeggingsElectricBlueB4A8T-UBZJ53.254_e8aaaacb-1586-432b-a4cd-111b0e1f7414.jpg?v=1679991384",
        name: "RUNNING LEGGINGS",
        description: "These collections take your training staples and give you something a little bit extra.",
        category: "leggings",
        color: "Electric Blue",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 42,
        ratings: 4.3,
        isInStock: true
      },
      {
        id: "cQm2vZEbjXyDUH7",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/IconRunningLeggingsElectricBlueB4A8T-UBZJ53.254_e8aaaacb-1586-432b-a4cd-111b0e1f7414.jpg?v=1679991384",
        name: "WARP KNIT TIGHTS",
        description: "Say hello to Warp Knit. Warp knit technology combines the ultimate lightweight fabric with freedom of movement and best level seamless technology to give you your most unique and delicate workout look yet. It’s all in the details.",
        category: "leggings",
        color: "Woodland Green",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
        ],
        price: 60,
        ratings: 3.9,
        isInStock: true
      },
      {
        id: "MbXONz0ZkAxdcRS",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/MetalShakerSteelGreyI2A6L-GBNK.1134.jpg?v=1684486055",
        name: "METAL SHAKER",
        description: "Whether you're shakin' or hydratin', you can always count on the Metal Shaker. It’s got a mixer built in to the lid, so you don’t have to fuss around with a loose mixing ball, and double wall insulation to keep your shakes at the temperature you want them. Then, it’s all brought together with a sleek, brushed metal finish.",
        category: "bottles",
        color: "Steel Grey",
        sizes: [
          { id: '1', size: 'onesize' },
        ],
        price: 20,
        ratings: 2.5,
        isInStock: true
      },
      {
        id: "p5fibwwXsQrnswT",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/GABO4207-BK-OS21.B-Edit_BK_306ad9d6-f440-4ac7-85b1-e2ed8661a30d.jpg?v=1664796998",
        name: "600ML SHAKER BOTTLE",
        description: "Fuelling your body is essential for the perfect workout. Whether you're shakin' or hydratin', you can always count on the Shaker Bottle. It's handy, hardwearing and with a pop of color, it looks great too.",
        category: "bottles",
        color: "Black",
        sizes: [
          { id: '1', size: 'onesize' },
        ],
        price: 10,
        ratings: 3.1,
        isInStock: true
      },
      {
        id: "a2sjyZTvFdjUyt9",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/EverydayToteLightGreyI2A1V-GBCM.jpg?v=1662407387",
        name: "EVERYDAY TOTE",
        description: "In world full of plastic bags, opt for tote instead. Our Everyday Tote Bag is durable, lightweight, and with its large main-entry space and front slip pockets, it works for just about anything your day has in store. Work? Tote. Gym? Tote. Shopping? Tote.",
        category: "bags",
        color: "Light Grey",
        sizes: [
          { id: '1', size: 'onesize' },
        ],
        price: 30,
        ratings: 4.5,
        isInStock: true
      },
      {
        id: "5gvYhn2npQdjaOZ",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/BoldBarrelBagBlackI2A1W-BBBB-1154.141.jpg?v=1668354897",
        name: "BOLD BARREL BAG",
        description: "A bold design for even bolder moves. Durable materials, practical pockets and compartments, and a striking Bold Gymshark wordmark combine to make these the only gym bags you’re ever gonna need.",
        category: "bags",
        color: "Black",
        sizes: [
          { id: '1', size: 'onesize' },
        ],
        price: 30,
        ratings: 4.8,
        isInStock: true
      },
      {
        id: "wvKInQLQ3HUpO7b",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/SleekBackpackBlackI1A8A-BBBB41_ZH_ZH.jpg?v=1688411814",
        name: "SLEEK BACKPACK",
        description: "A bag that carries everything you could need it to and looks as good as you could want it to? It’s here.",
        category: "bags",
        color: "Black",
        sizes: [
          { id: '1', size: 'onesize' },
        ],
        price: 45,
        ratings: 4.8,
        isInStock: true
      },
      {
        id: "F0F6cpggJJupfob",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/C114_REST_DAY_MB8310_62e92e4e-a1da-4566-8b0d-4b2e94a16d77.jpg?v=1671440989",
        name: "REST DAY LOUNGE HOODIE",
        description: "Take a moment for yourself in Rest Day. The softest fabrics meet stylish, easy-wear designs to make this collection perfect for your next rest day look",
        category: "hoodies",
        color: "Coffee Brown",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 50,
        reducedPrice: 20,
        ratings: 1.5,
        isInStock: true
      },
      {
        id: "JLtnVOPOlsjQ9gF",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/files/IronworksOversizedHoodieGSWashedBurgundyB7A9Y-RBQS-0821.jpg?v=1689579323",
        name: "COMMITTED TO THE CRAFT HOODIE",
        description: "Step up and rep out in the Gymshark Ironworks collection.",
        category: "hoodies",
        color: "Red",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 60,
        reducedPrice: 30,
        ratings: 3.8,
        isInStock: true
      },
      {
        id: "ccBboTuMWLCcL3B",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/LegacyDropArmHoodieHoyaGreenA1A8E-EBRF.jpg?v=1666178069",
        name: "LEGACY DROP ARM HOODIE",
        description: "All that’s left is for you to put in the work, and build your own legacy.",
        category: "hoodies",
        color: "Hoya Green",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 36,
        ratings: 2.8,
        isInStock: true
      },
      {
        id: "kDbgPr5OsqQZglw",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/CrestCrew_Slim_CoreOliveA2A1V-EBF1.A_ZH_ZH_3cb78d5f-254f-4a44-a81f-336edd8301dd.jpg?v=1644493801",
        name: "CREST SWEATSHIRT",
        description: "Rest day the Crest way in the consistently comfortable and casually stylish Crest Sweatshirt.",
        category: "sweatshirts",
        color: "Core Olive",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 32,
        ratings: 3.7,
        isInStock: true
      },
      {
        id: "Yu5UEypMEKazhOt",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/TrainingZip-UpJacketBlackB2A4B-BBBB.A-Edit_ZH_5d805c9b-5df7-43aa-90a5-a4a6bc4eaaff.jpg?v=1666196944",
        name: "TRAINING JACKET",
        description: "The zip up you’ll want in your gym locker. High neck, deep zipped pockets and full-length zip, made of breathable material, perfect to see you through any outdoor workout, or throw on after any indoor one.",
        category: "jackets",
        color: "Black",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 40,
        ratings: 4.4,
        isInStock: true
      },
      {
        id: "YcVXMOTVQhzpQHT",
        image: "https://cdn.shopify.com/s/files/1/0098/8822/products/ELEVATEZIPUPRoseBrownB3A7M-NBH1651_43c96406-23c0-4ada-9024-feca05f3b66c.jpg?v=1665512238",
        name: "ELEVATE ZIP JACKET",
        description: "Elevate is about seizing the Sunday in every day, whether that’s getting your morning coffee or hitting your hot yoga class",
        category: "jackets",
        color: "Rose Brown",
        sizes: [
          { id: '1', size: 'XS' },
          { id: '2', size: 'S' },
          { id: '3', size: 'M' },
          { id: '4', size: 'L' },
          { id: '5', size: 'XL' },
        ],
        price: 60,
        ratings: 4.3,
        isInStock: false
      }
    ]
  }

module.exports = products;
